version: '3'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
    networks:
      - key-manager
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091
    networks:
      - key-manager
  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - key-manager
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    networks:
      - key-manager
    depends_on:
      - postgres
    restart: unless-stopped
  key-manager-grpc:
    image: "key-manager-grpc"
    ports:
      - 50051:50051
    networks:
      - key-manager
    depends_on:
      - bcb
      - erp-itau
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/pix
      DB_USR: postgres
      DB_PSW: postgres
      ITAU_ERP_URL: http://erp-itau:9091/api/v1
      CBC_URL: http://bcb:8082/api/v1
  key-manager-rest:
    build: ./
    ports:
      - 8080:8080
    networks:
      - key-manager
    depends_on:
      - key-manager-grpc
    restart: on-failure
    environment:
      KEY_MANAGER_URL: key-manager-grpc:50051
volumes:
  postgres-volume:
  pgadmin-volume:
networks:
  key-manager:
    driver: "bridge"